"""Inelastic phonon transport tools kept separate from the ballistic core.

Theory modules are approximation-first under ``negfpy.inelastic.approximations``.
Toy models such as FPU-alpha and phi^4 remain separate helpers/examples.
"""

from .approximations import (
    FourthOrderInteraction,
    FourthOrderLowestOrderModel,
    FourthOrderMeanFieldModel,
    FourthOrderSCBAModel,
    ThirdOrderInteraction,
    ThirdOrderLowestOrderModel,
    ThirdOrderMeanFieldModel,
    ThirdOrderSCBAModel,
    fourth_order_lowest_order_model_from_covariance,
    fourth_order_lowest_order_model_from_device,
    fourth_order_lowest_order_self_energy,
    fourth_order_mean_field_model_from_covariance,
    fourth_order_mean_field_model_from_device,
    fourth_order_mean_field_self_energy,
    fourth_order_scba_model_from_device,
    fourth_order_scba_self_energy,
    third_order_lowest_order_model_from_device,
    third_order_lowest_order_self_energy,
    third_order_mean_field_model_from_displacement,
    third_order_mean_field_self_energy,
    third_order_scba_model_from_device,
    third_order_scba_self_energy,
)
from .base import InelasticSolveInfo, PPSelfEnergyModel
from .benchmarks import (
    fpu_alpha_lowest_order_conductance_sweep,
    phi4_compare_conductance_sweeps,
    phi4_conductance_sweep,
)
from .fpu_alpha import (
    FPUAlphaParams,
    fpu_alpha_lowest_order_model,
    fpu_alpha_scba_model,
    fpu_alpha_third_order_interaction,
)
from .phenomenology import PowerLawPPSelfEnergy
from .phi4 import Phi4Params, phi4_fourth_order_interaction, phi4_lowest_order_model, phi4_mean_field_model, phi4_scba_model
from .solver import device_green_function_inelastic, transmission_inelastic
from .wang import (
    LorentzDrudeBath,
    QuarticSCMFBenchmarkCase,
    quartic_scmf_current_vs_temperature,
    quartic_scmf_static_self_energy,
    wang_lorentz_drude_bath_from_epsilon,
    wang_review_fig4_audit,
    wang_review_fig4_paper_convention_spec,
    wang_review_fig4_paper_convention_sweep,
    wang_review_fig4_one_particle_cases,
    wang_review_fig4_one_particle_cases_si,
    wang_review_fig4_two_particle_cases_si,
    wang_review_hbar_effective_si,
    wang_review_kb_effective_si,
    wang_review_fig4_two_particle_cases,
)
from .wang0701164 import (
    CubicOnsiteChainParams,
    cubic_onsite_current,
    cubic_onsite_current_exact,
    cubic_onsite_eq84_numeric_decomposition,
    cubic_onsite_effective_transmission,
    cubic_onsite_effective_transmission_paper_derivative,
    cubic_onsite_effective_transmission_paper_derivative_numeric,
    cubic_onsite_g0_lesser,
    cubic_onsite_g0_retarded,
    cubic_onsite_lead_self_energies,
    cubic_onsite_lowest_order_self_energies,
    cubic_onsite_lowest_order_self_energies_exact,
    wang0701164_compare_sweep_to_digitized,
    wang0701164_compare_sweep_to_vector_pdf,
    wang0701164_extract_fig5_vector_curves,
    wang0701164_fig5_lowest_order_conductance_sweep,
    wang0701164_fig5_params,
    wang0701164_fig5_spec,
    wang0701164_kb_effective_si,
    wang0701164_load_digitized_fig5_curves,
    wang0701164_load_vector_fig5_curves,
    wang0701164_paper_unit_factors,
)

__all__ = [
    "PPSelfEnergyModel",
    "InelasticSolveInfo",
    "PowerLawPPSelfEnergy",
    "device_green_function_inelastic",
    "transmission_inelastic",
    "fpu_alpha_lowest_order_conductance_sweep",
    "phi4_conductance_sweep",
    "phi4_compare_conductance_sweeps",
    "FPUAlphaParams",
    "fpu_alpha_third_order_interaction",
    "fpu_alpha_lowest_order_model",
    "fpu_alpha_scba_model",
    "Phi4Params",
    "phi4_fourth_order_interaction",
    "phi4_lowest_order_model",
    "phi4_mean_field_model",
    "phi4_scba_model",
    "LorentzDrudeBath",
    "QuarticSCMFBenchmarkCase",
    "quartic_scmf_static_self_energy",
    "quartic_scmf_current_vs_temperature",
    "wang_lorentz_drude_bath_from_epsilon",
    "wang_review_fig4_audit",
    "wang_review_fig4_paper_convention_spec",
    "wang_review_fig4_paper_convention_sweep",
    "wang_review_fig4_one_particle_cases",
    "wang_review_fig4_two_particle_cases",
    "wang_review_fig4_one_particle_cases_si",
    "wang_review_fig4_two_particle_cases_si",
    "wang_review_kb_effective_si",
    "wang_review_hbar_effective_si",
    "CubicOnsiteChainParams",
    "cubic_onsite_g0_retarded",
    "cubic_onsite_g0_lesser",
    "cubic_onsite_lead_self_energies",
    "cubic_onsite_lowest_order_self_energies",
    "cubic_onsite_current",
    "cubic_onsite_current_exact",
    "cubic_onsite_eq84_numeric_decomposition",
    "cubic_onsite_effective_transmission",
    "cubic_onsite_effective_transmission_paper_derivative",
    "cubic_onsite_effective_transmission_paper_derivative_numeric",
    "wang0701164_load_digitized_fig5_curves",
    "wang0701164_compare_sweep_to_digitized",
    "wang0701164_load_vector_fig5_curves",
    "wang0701164_extract_fig5_vector_curves",
    "wang0701164_compare_sweep_to_vector_pdf",
    "wang0701164_fig5_spec",
    "wang0701164_fig5_params",
    "wang0701164_fig5_lowest_order_conductance_sweep",
    "wang0701164_kb_effective_si",
    "wang0701164_paper_unit_factors",
    "cubic_onsite_lowest_order_self_energies_exact",
    "ThirdOrderInteraction",
    "ThirdOrderLowestOrderModel",
    "ThirdOrderMeanFieldModel",
    "ThirdOrderSCBAModel",
    "third_order_lowest_order_self_energy",
    "third_order_lowest_order_model_from_device",
    "third_order_mean_field_self_energy",
    "third_order_mean_field_model_from_displacement",
    "third_order_scba_model_from_device",
    "third_order_scba_self_energy",
    "FourthOrderInteraction",
    "FourthOrderLowestOrderModel",
    "FourthOrderMeanFieldModel",
    "FourthOrderSCBAModel",
    "fourth_order_lowest_order_self_energy",
    "fourth_order_lowest_order_model_from_covariance",
    "fourth_order_lowest_order_model_from_device",
    "fourth_order_mean_field_self_energy",
    "fourth_order_mean_field_model_from_covariance",
    "fourth_order_mean_field_model_from_device",
    "fourth_order_scba_model_from_device",
    "fourth_order_scba_self_energy",
]
